# setup.ps1
# One-time setup wizard for LinkedIn Job Agent.
# Run this as Administrator the first time you set up the agent.

$ErrorActionPreference = "Stop"
$ProjectDir = $PSScriptRoot
$JobAgentDir = "C:\Users\$env:USERNAME\AppData\Local\JobAgent"

Write-Host ""
Write-Host "============================================"
Write-Host "  LinkedIn Job Agent — Setup Wizard"
Write-Host "============================================"
Write-Host ""

# ── 1. Check Claude Code ──────────────────────────────
$ClaudePath = "C:\Users\$env:USERNAME\AppData\Roaming\npm\claude.cmd"
if (-not (Test-Path $ClaudePath)) {
    Write-Host "ERROR: Claude Code CLI not found at:" -ForegroundColor Red
    Write-Host "  $ClaudePath" -ForegroundColor Red
    Write-Host ""
    Write-Host "Install it with:"
    Write-Host "  npm install -g @anthropic-ai/claude-code"
    Write-Host ""
    Write-Host "Then re-run this setup."
    exit 1
}
Write-Host "[OK] Claude Code found." -ForegroundColor Green

# ── 2. Check CV ───────────────────────────────────────
$CvPath = "$ProjectDir\cv\CV.pdf"
if (-not (Test-Path $CvPath)) {
    Write-Host ""
    Write-Host "WARNING: CV not found at cv\CV.pdf" -ForegroundColor Yellow
    Write-Host "Place your CV as cv\CV.pdf before running the agent."
    Write-Host "(Setup will continue, but the agent needs the CV to score jobs.)"
}
else {
    Write-Host "[OK] CV found." -ForegroundColor Green
}

# ── 3. Read email from user_config.yaml ───────────────
$UserConfigPath = "$ProjectDir\config\user_config.yaml"
if (-not (Test-Path $UserConfigPath)) {
    Write-Host "ERROR: config\user_config.yaml not found." -ForegroundColor Red
    exit 1
}

$ConfigRaw = Get-Content $UserConfigPath -Raw

$EmailMatch = [regex]::Match($ConfigRaw, 'email:\s*"([^"]+)"')
if (-not $EmailMatch.Success -or $EmailMatch.Groups[1].Value -eq "your.email@gmail.com") {
    Write-Host ""
    Write-Host "Please enter your Gmail address:"
    $UserEmail = Read-Host "Email"
    $ConfigRaw = $ConfigRaw -replace 'email:\s*"[^"]*"', "email: `"$UserEmail`""
}
else {
    $UserEmail = $EmailMatch.Groups[1].Value
    Write-Host "[OK] Email: $UserEmail" -ForegroundColor Green
}

$NameMatch = [regex]::Match($ConfigRaw, 'name:\s*"([^"]+)"')
if (-not $NameMatch.Success -or $NameMatch.Groups[1].Value -eq "Your Name") {
    Write-Host ""
    Write-Host "Please enter your full name (used in job fit analysis):"
    $UserName = Read-Host "Full name"
    $ConfigRaw = $ConfigRaw -replace 'name:\s*"[^"]*"', "name: `"$UserName`""
}
else {
    $UserName = $NameMatch.Groups[1].Value
    Write-Host "[OK] Name: $UserName" -ForegroundColor Green
}

[System.IO.File]::WriteAllText($UserConfigPath, $ConfigRaw, [System.Text.Encoding]::UTF8)

# ── 4. Gmail App Password ─────────────────────────────
Write-Host ""
Write-Host "You need a Gmail App Password (not your regular Gmail password)."
Write-Host "Steps:"
Write-Host "  1. Go to https://myaccount.google.com/apppasswords"
Write-Host "  2. Sign in and create an App Password for 'Mail'"
Write-Host "  3. Copy the 16-character code"
Write-Host ""
$AppPassword = Read-Host "Paste your Gmail App Password here (input is hidden)" -AsSecureString
$AppPasswordPlain = [System.Runtime.InteropServices.Marshal]::PtrToStringAuto(
    [System.Runtime.InteropServices.Marshal]::SecureStringToBSTR($AppPassword)
)

# ── 5. Create AppData folder and files ────────────────
New-Item -ItemType Directory -Force -Path $JobAgentDir | Out-Null

# Write personalized send_email.ps1
$SendEmailScript = @"
# send_email.ps1 — auto-generated by setup.ps1 — do not edit manually
param(
    [Parameter(Mandatory=`$true)] [string] `$Subject,
    [string] `$HtmlBody,
    [string] `$HtmlBodyFile
)

if (`$HtmlBodyFile) {
    if (-not (Test-Path `$HtmlBodyFile)) { Write-Error "HtmlBodyFile not found: `$HtmlBodyFile"; exit 1 }
    `$HtmlBody = Get-Content `$HtmlBodyFile -Raw -Encoding UTF8
}
if (-not `$HtmlBody) { Write-Error "Either -HtmlBody or -HtmlBodyFile must be provided."; exit 1 }

`$FromAddress = "$UserEmail"
`$ToAddress   = "$UserEmail"
`$SmtpServer  = "smtp.gmail.com"
`$SmtpPort    = 587
`$CredsFile   = "`$PSScriptRoot\gmail_creds.txt"

if (-not (Test-Path `$CredsFile)) { Write-Error "Credentials file not found. Re-run setup.ps1."; exit 1 }

try {
    `$Encrypted  = (Get-Content `$CredsFile -Raw).Trim()
    `$SecurePass = `$Encrypted | ConvertTo-SecureString
    `$Creds      = New-Object System.Management.Automation.PSCredential(`$FromAddress, `$SecurePass)
} catch { Write-Error "Failed to decrypt credentials: `$_"; exit 1 }

try {
    Send-MailMessage ``
        -From       `$FromAddress ``
        -To         `$ToAddress ``
        -Subject    `$Subject ``
        -Body       `$HtmlBody ``
        -BodyAsHtml ``
        -SmtpServer `$SmtpServer ``
        -Port       `$SmtpPort ``
        -UseSsl ``
        -Credential `$Creds ``
        -Encoding   UTF8
    Write-Host "Email sent successfully to `$ToAddress"
} catch { Write-Error "Failed to send email: `$_"; exit 1 }
"@
[System.IO.File]::WriteAllText("$JobAgentDir\send_email.ps1", $SendEmailScript, [System.Text.Encoding]::UTF8)

# Encrypt and save App Password (DPAPI — machine + user specific)
$SecurePass = ConvertTo-SecureString $AppPasswordPlain -AsPlainText -Force
$Encrypted  = $SecurePass | ConvertFrom-SecureString
[System.IO.File]::WriteAllText("$JobAgentDir\gmail_creds.txt", $Encrypted, [System.Text.Encoding]::UTF8)

Write-Host ""
Write-Host "[OK] Credentials encrypted and saved." -ForegroundColor Green
Write-Host "[OK] send_email.ps1 created in AppData." -ForegroundColor Green

# ── 6. Task Scheduler ─────────────────────────────────
Write-Host ""
$Answer = Read-Host "Set up automatic daily run at 8:00 AM via Task Scheduler? (Y/N)"
if ($Answer -match "^[Yy]") {
    $ScriptPath = "$ProjectDir\run_job_agent.ps1"
    $TaskAction = "powershell.exe -NoProfile -ExecutionPolicy Bypass -WindowStyle Hidden -File `"$ScriptPath`""
    try {
        schtasks.exe /Create /TN "JobAgentDailyDigest" /SC DAILY /ST "08:00" /TR $TaskAction /F 2>&1 | Out-Null
        Write-Host "[OK] Task Scheduler task created. Agent will run daily at 8:00 AM." -ForegroundColor Green
    } catch {
        Write-Host "WARNING: Could not create Task Scheduler task: $_" -ForegroundColor Yellow
        Write-Host "You can run the agent manually with: .\run_job_agent.ps1"
    }
}

# ── 7. Claude Gmail permission reminder ───────────────
Write-Host ""
Write-Host "============================================"
Write-Host "  IMPORTANT: Connect Gmail to Claude"
Write-Host "============================================"
Write-Host ""
Write-Host "The agent reads your Gmail via Claude's Gmail integration."
Write-Host "If you haven't done this yet:"
Write-Host "  1. Go to https://claude.ai"
Write-Host "  2. Settings → Integrations"
Write-Host "  3. Connect your Gmail account"
Write-Host ""
Write-Host "============================================"
Write-Host "  Setup complete!"
Write-Host "============================================"
Write-Host ""
Write-Host "Next steps:"
Write-Host "  - Make sure cv\CV.pdf is in place"
Write-Host "  - Review config\job_preferences.yaml"
Write-Host "  - Run manually to test: .\run_job_agent.ps1"
Write-Host ""
